In [1]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.14.0+cpu
False


In [2]:
import torch
x = torch.tensor([1,2,3,4])
x

tensor([1, 2, 3, 4])

In [3]:
y = torch.tensor([
    [1,2],
    [3,4]
])
y

tensor([[1, 2],
        [3, 4]])

In [4]:
z = torch.zeros(5,6)
z

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [5]:
o = torch.ones(5,6)
o

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [6]:
r = torch.rand(5,6)
r

tensor([[2.0260e-01, 2.1916e-01, 2.1904e-01, 7.2864e-01, 2.3256e-01, 2.5374e-04],
        [1.1443e-01, 3.9064e-01, 7.3248e-01, 6.6274e-01, 2.4600e-01, 5.7844e-01],
        [5.8163e-01, 1.1937e-01, 7.5766e-01, 1.9035e-01, 4.5646e-01, 1.5562e-01],
        [3.5672e-02, 1.4221e-01, 5.8629e-01, 1.4545e-01, 4.7446e-01, 3.4450e-01],
        [1.9298e-01, 3.7619e-01, 2.5688e-01, 4.3245e-01, 8.4691e-01, 9.3351e-02]])

In [7]:
import torch

x = torch.tensor([10, 20, 30])

print(x)
print(type(x))
print(x.shape)
print(x.dtype)

tensor([10, 20, 30])
<class 'torch.Tensor'>
torch.Size([3])
torch.int64


In [8]:
i = torch.tensor([10,20,30,40])
print(i[0])
print(i[1])
print(i[2])

tensor(10)
tensor(20)
tensor(30)


In [9]:
i_2 = torch.tensor([
    [10,20,30],
    [40,50,60]
])
print(i_2[0,2])
print(i_2[1,1])

tensor(30)
tensor(50)


In [10]:
sohail = torch.tensor([10,20,33])
subbi = torch.tensor([15,25,40])
print(sohail+subbi)
print(sohail-subbi)
print(sohail*subbi)

tensor([25, 45, 73])
tensor([-5, -5, -7])
tensor([ 150,  500, 1320])


In [11]:
# Scalar Operation
s = torch.tensor([2,5,7,3])
print(s*2)

tensor([ 4, 10, 14,  6])


In [12]:
import numpy as np
arr = np.array([10,20,30])
n = torch.tensor(arr)
print(n)
print(arr)

tensor([10, 20, 30])
[10 20 30]
