In [1]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.14.0+cpu
False


In [2]:
import torch
x = torch.tensor([1,2,3,4])
x

tensor([1, 2, 3, 4])

In [3]:
y = torch.tensor([
    [1,2],
    [3,4]
])
y

tensor([[1, 2],
        [3, 4]])

In [4]:
z = torch.zeros(5,6)
z

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [5]:
o = torch.ones(5,6)
o

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [6]:
r = torch.rand(5,6)
r

tensor([[0.1614, 0.4534, 0.9136, 0.6714, 0.3690, 0.1398],
        [0.0493, 0.3532, 0.3711, 0.1163, 0.1696, 0.6934],
        [0.3946, 0.8257, 0.1869, 0.3448, 0.8465, 0.8136],
        [0.5236, 0.9542, 0.5980, 0.0423, 0.5318, 0.7208],
        [0.3218, 0.4487, 0.8142, 0.3081, 0.4083, 0.4822]])

In [7]:
import torch

x = torch.tensor([10, 20, 30])

print(x)
print(type(x))
print(x.shape)
print(x.dtype)

tensor([10, 20, 30])
<class 'torch.Tensor'>
torch.Size([3])
torch.int64


In [8]:
i = torch.tensor([10,20,30,40])
print(i[0])
print(i[1])
print(i[2])

tensor(10)
tensor(20)
tensor(30)


In [9]:
i_2 = torch.tensor([
    [10,20,30],
    [40,50,60]
])
print(i_2[0,2])
print(i_2[1,1])

tensor(30)
tensor(50)


In [10]:
sohail = torch.tensor([10,20,33])
subbi = torch.tensor([15,25,40])
print(sohail+subbi)
print(sohail-subbi)
print(sohail*subbi)

tensor([25, 45, 73])
tensor([-5, -5, -7])
tensor([ 150,  500, 1320])


In [11]:
# Scalar Operation
s = torch.tensor([2,5,7,3])
print(s*2)

tensor([ 4, 10, 14,  6])


In [12]:
import numpy as np
arr = np.array([10,20,30])
n = torch.tensor(arr)
print(n)
print(arr)

tensor([10, 20, 30])
[10 20 30]
